<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>md5er.ico</ApplicationIcon>
    <Version>1.0.1</Version>
    <AssemblyVersion>1.0.1.0</AssemblyVersion>
    <FileVersion>1.0.1.0</FileVersion>
    <Company>James Hobson</Company>
    <Product>md5er</Product>
    <Copyright>Copyright © 2026 James Hobson</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="md5er.ico"/>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="md5er.Tests\**" />
    <EmbeddedResource Remove="md5er.Tests\**" />
    <None Remove="md5er.Tests\**" />
    <Page Remove="md5er.Tests\**" />
  </ItemGroup>

</Project>
